### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by priyamjyoti** [sportingCode/SWIMmeR#1]
> getLibrary()
> getSource()
> input_parameter <- config()
> input_file <- inputFiles()
Error in `[.data.frame`(data, , c(control, case)) : 
  undefined columns selected
Called from: `[.data.frame`(data, , c(control, case))

**Comment by mariaventimiglia** [comment]
I had the same warning, how may it be solved?

**Comment by sportingCode** [comment]
If you are using the example BRCA dataset and have downloaded the SWIMmer code from GitHub as a single .zip file, you may not have correctly downloaded the entire RNAseq data matrix. I recommend downloading the matrix separately from here: https://github.com/sportingCode/SWIMmeR/blob/main/code/project/TCGA/dataset/brca/matrix/matrice__brca_RNASeq.txt and placing it in the “matrix” folder. This should allow the code to run correctly.

**Comment by mariaventimiglia** [comment]
Thanks! Now it works
