### ISSUE TITLE
error

### ISSUE THREAD

**Issue by raulpironacnr** [sportingCode/SWIMmeR#2]
Error in z >= 2.5 & P > 0.3 && P <= 0.75 : 
  'length = 461' in coercion to 'logical(1)'
Called from: getNodeRole(y, z, P)

**Comment by raulpironacnr** [comment]
solved adding () and replacing && with & in getNodeRole.R file:

example:

type[(z < 2.5) & (P > 0.04)  & (P <= 0.625)]

**Comment by raulpironacnr** [comment]
This was due to the updated R version and not from the code itself.

**Comment by sportingCode** [comment]
We fixed the code to avoid this issue for the new version of R
